### PR TITLE
LegalCommandTest legal_e2() #190

### PR DESCRIPTION
**Pull request by kaifkh20**
Closes https://github.com/chesslablab/chess-server/issues/190

### CODE REVIEW

**Comment by programarivm** [comment]
@kaifkh20 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/chess-server/blob/master/CONTRIBUTING.md).

Let me just point out that the PR for this issue should be sent from October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by kaifkh20** [comment]
Should I close this?

**Comment by programarivm** [comment]
No worries, let's review this pull request starting October 1st. 

Keep it up,

**Comment by kaifkh20** [comment]
Any updates on this?

**Pull request closed without merging**
